### ISSUE TITLE
CUDA Illegal Memory Access Error

### ISSUE THREAD

**Issue by aperire** [cocktailpeanut/fluxgym#289]
Hi, when training a lora on a custom Flux FP8 checkpoint, I have enountered the following error.

I never had this issue before with the same config, but it seems to happen everytime mid-training since today.

What would be the reason?

```
[2025-01-09 02:45:30] [INFO] File "C:\pinokio\api\fluxgym.git\sd-scripts\flux_train_network.py", line 583, in <module>
[2025-01-09 02:45:30] [INFO] trainer.train(args)
[2025-01-09 02:45:30] [INFO] File "C:\pinokio\api\fluxgym.git\sd-scripts\train_network.py", line 1251, in train
[2025-01-09 02:45:30] [INFO] accelerator.backward(loss)
[2025-01-09 02:45:30] [INFO] File "C:\pinokio\api\fluxgym.git\env\lib\site-packages\accelerate\accelerator.py", line 2159, in backward
[2025-01-09 02:45:30] [INFO] loss.backward(**kwargs)
[2025-01-09 02:45:30] [INFO] File "C:\pinokio\api\fluxgym.git\env\lib\site-packages\torch\_tensor.py", line 581, in backward
[2025-01-09 02:45:30] [INFO] torch.autograd.backward(
[2025-01-09 02:45:30] [INFO] File "C:\pinokio\api\fluxgym.git\env\lib\site-packages\torch\autograd\__init__.py", line 347, in backward
[2025-01-09 02:45:30] [INFO] _engine_run_backward(
[2025-01-09 02:45:30] [INFO] File "C:\pinokio\api\fluxgym.git\env\lib\site-packages\torch\autograd\graph.py", line 825, in _engine_run_backward
[2025-01-09 02:45:30] [INFO] return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
[2025-01-09 02:45:30] [INFO] RuntimeError: CUDA error: an illegal memory access was encountered
[2025-01-09 02:45:30] [INFO] CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
[2025-01-09 02:45:30] [INFO] For debugging consider passing CUDA_LAUNCH_BLOCKING=1
[2025-01-09 02:45:30] [INFO] Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
[2025-01-09 02:45:30] [INFO] 
[2025-01-09 02:45:30] [INFO] steps:   9%|▉         | 469/5250 [1:02:27<10:36:43,  7.99s/it, avr_loss=0.34]
[2025-01-09 02:45:32] [INFO] Traceback (most recent call last):
[2025-01-09 02:45:32] [INFO] File "C:\pinokio\bin\miniconda\lib\runpy.py", line 196, in _run_module_as_main
[2025-01-09 02:45:32] [INFO] return _run_code(code, main_globals, None,
[2025-01-09 02:45:32] [INFO] File "C:\pinokio\bin\miniconda\lib\runpy.py", line 86, in _run_code
[2025-01-09 02:45:32] [INFO] exec(code, run_globals)
[2025-01-09 02:45:32] [INFO] File "C:\pinokio\api\fluxgym.git\env\Scripts\accelerate.exe\__main__.py", line 7, in <module>
[2025-01-09 02:45:32] [INFO] sys.exit(main())
[2025-01-09 02:45:32] [INFO] File "C:\pinokio\api\fluxgym.git\env\lib\site-packages\accelerate\commands\accelerate_cli.py", line 48, in main
[2025-01-09 02:45:32] [INFO] args.func(args)
[2025-01-09 02:45:32] [INFO] File "C:\pinokio\api\fluxgym.git\env\lib\site-packages\accelerate\commands\launch.py", line 1106, in launch_command
[2025-01-09 02:45:32] [INFO] simple_launcher(args)
[2025-01-09 02:45:32] [INFO] File "C:\pinokio\api\fluxgym.git\env\lib\site-packages\accelerate\commands\launch.py", line 704, in simple_launcher
[2025-01-09 02:45:32] [INFO] raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
[2025-01-09 02:45:32] [INFO] subprocess.CalledProcessError: Command '['C:\\pinokio\\api\\fluxgym.git\\env\\Scripts\\python.exe', 'sd-scripts/flux_train_network.py', '--pretrained_model_name_or_path', 'C:\\pinokio\\api\\fluxgym.git\\models\\unet\\nsfw\\redcraftCADSCommercial_revealNSFW.safetensors', '--clip_l', 'C:\\pinokio\\api\\fluxgym.git\\models\\clip\\clip_l.safetensors', '--t5xxl', 'C:\\pinokio\\api\\fluxgym.git\\models\\clip\\t5xxl_fp16.safetensors', '--ae', 'C:\\pinokio\\api\\fluxgym.git\\models\\vae\\ae.sft', '--cache_latents_to_disk', '--save_model_as', 'safetensors', '--sdpa', '--persistent_data_loader_workers', '--max_data_loader_n_workers', '2', '--seed', '42', '--gradient_checkpointing', '--mixed_precision', 'bf16', '--save_precision', 'bf16', '--network_module', 'networks.lora_flux', '--network_dim', '32', '--optimizer_type', 'adafactor', '--optimizer_args', 'relative_step=False', 'scale_parameter=False', 'warmup_init=False', '--split_mode', '--network_args', 'train_blocks=single', '--lr_scheduler', 'cosine', '--lr_warmup_steps', '0.2', '--lr_decay_steps', '0.8', '--max_grad_norm', '0.0', '--sample_prompts=C:\\pinokio\\api\\fluxgym.git\\outputs\\haewon-nsfw\\sample_prompts.txt', '--sample_every_n_steps=200', '--learning_rate', '1e-4', '--cache_text_encoder_outputs', '--cache_text_encoder_outputs_to_disk', '--fp8_base', '--highvram', '--max_train_epochs', '30', '--save_every_n_epochs', '4', '--dataset_config', 'C:\\pinokio\\api\\fluxgym.git\\outputs\\haewon-nsfw\\dataset.toml', '--output_dir', 'C:\\pinokio\\api\\fluxgym.git\\outputs\\haewon-nsfw', '--output_name', 'haewon-nsfw', '--timestep_sampling', 'shift', '--discrete_flow_shift', '3.1582', '--model_prediction_type', 'raw', '--guidance_scale', '1', '--loss_type', 'l2', '--network_alpha', '16']' returned non-zero exit status 1.
[2025-01-09 02:45:32] [ERROR] Command exited with code 1
[2025-01-09 02:45:32] [INFO] Runner: <LogsViewRunner nb_logs=349 exit_code=1>
```

**Comment by aperire** [comment]
Hardware: 4070 Super (12G)

**Comment by aperire** [comment]
Issue solved. I deleted GPU Tweak software (ASUS) and rebooted to make it work.
