### ISSUE TITLE
INFO: This is taking longer than usual. You might need to provide the dependency resolver....

### ISSUE THREAD

**Issue by eariel** [cocktailpeanut/fluxgym#458]
Hi, I'm new to Fluxgym and I'm installing it on RunPod. The first time I tried it following the instructions on this page, I was able to get it working in less than 30 minutes. At the end, I deleted the pod since I wasn't going to use it for several days.
For several days now, I've been trying to create a new instance using the same template and instructions, but after literally waiting hours, I had to cancel it. Does this happen to anyone else?
On the line:
pip install -r requirements.txt
the process takes a long time to install each of the NVIDIA modules.

Does anyone know if this is due to bandwidth issues, the type of template, or if there was some change in the installation process?
Here is part of the logs where the process takes hours:

Collecting nvidia-nccl-cu12==2.27.3 
Using cached nvidia_nccl_cu12-2.27.3-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (322.4 MB)
INFO: This is taking longer than usual. You might need to provide the dependency resolve with stricter constraints to reduce runtime. See https://pip.pypa.io/warnings/backtracking for guidance. If you want to abort this run, press Ctrl + C.
INFO: This is taking longer than usual. You might need to provide the dependency resolve with stricter constraints to reduce runtime. See https://pip.pypa.io/warnings/backtracking for guidance. If you want to abort this run, press Ctrl + C.
INFO: This is taking longer than usual. You might need to provide the dependency resolve with stricter constraints to reduce runtime. See https://pip.pypa.io/warnings/backtracking for guidance. If you want to abort this run, press Ctrl + C.
INFO: This is taking longer than usual. You might need to provide the dependency resolve with stricter constraints to reduce runtime. See https://pip.pypa.io/warnings/backtracking for guidance. If you want to abort this run, press Ctrl + C.
INFO: This is taking longer than usual. You might need to provide the dependency resolve with stricter constraints to reduce runtime. See https://pip.pypa.io/warnings/backtracking for guidance. If you want to abort this run, press Ctrl + C.
INFO: This is taking longer than usual. You might need to provide the dependency resolve with stricter constraints to reduce runtime. See https://pip.pypa.io/warnings/backtracking for guidance. If you want to abort this run, press Ctrl + C.
INFO: This is taking longer than usual. You might need to provide the dependency resolve with stricter constraints to reduce runtime. See https://pip.pypa.io/warnings/backtracking for guidance. If you want to abort this run, press Ctrl + C.
INFO: This is taking longer than usual. You might need to provide the dependency resolve with stricter constraints to reduce runtime. See https://pip.pypa.io/warnings/backtracking for guidance. If you want to abort this run, press Ctrl + C.
INFO: pip is looking at multiple versions of nvidia-nvtx-cu12 to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of nvidia-cusparselt-cu12 to determine which version is compatible with other requirements. This could take a while.
Collecting nvidia-cusparselt-cu12==0.7.1 
Using cached nvidia_cusparselt_cu12-0.7.1-py3-none-manylinux2014_x86_64.whl (287.2 MB)
INFO: This is taking longer than usual. You might need to provide the dependency resolve with stricter constraints to reduce runtime. See https://pip.pypa.io/warnings/backtracking for guidance. If you want to abort this run, press Ctrl + C.
INFO: pip is looking at multiple versions of nvidia-nvjitlink-cu12 to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of nvidia-cusparse-cu12 to determine which version is compatible with other requirements. This could take a while.
Collecting nvidia-cusparse-cu12==12.5.8.93 
Using cached nvidia_cusparse_cu12-12.5.8.93-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (288.2 MB)
INFO: This is taking longer than usual. You might need to provide the dependency resolve with stricter constraints to reduce runtime. See https://pip.pypa.io/warnings/backtracking for guidance. If you want to abort this run, press Ctrl + C.
INFO: pip is looking at multiple versions of nvidia-nccl-cu12 to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of nvidia-cusolver-cu12 to determine which version is compatible with other requirements. This could take a while.
Collecting nvidia-cusolver-cu12==11.7.3.90 
  Using cached nvidia_cusolver_cu12-11.7.3.90-py3-none-manylinux_2_27_x86_64.whl (267.5 MB)
INFO: This is taking longer than usual. You might need to provide the dependency resolver with stricter constraints to reduce runtime. See https://pip.pypa.io/warnings/backtracking for guidance. If you want to abort this run, press Ctrl + C.
INFO: pip is looking at multiple versions of nvidia-cusparselt-cu12 to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of nvidia-curand-cu12 to determine which version is compatible with other requirements. This could take a while.
Collecting nvidia-curand-cu12==10.3.9.90
  Using cached nvidia_curand_cu12-10.3.9.90-py3-none-manylinux_2_27_x86_64.whl (63.6 MB)
INFO: This is taking longer than usual. You might need to provide the dependency resolver with stricter constraints to reduce runtime. See https://pip.pypa.io/warnings/backtracking for guidance. If you want to abort this run, press Ctrl + C.
INFO: pip is looking at multiple versions of nvidia-cusparse-cu12 to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of nvidia-cufile-cu12 to determine which version is compatible with other requirements. This could take a while.
Collecting nvidia-cufile-cu12==1.13.1.3
  Using cached nvidia_cufile_cu12-1.13.1.3-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (1.2 MB)
INFO: This is taking longer than usual. You might need to provide the dependency resolver with stricter constraints to reduce runtime. See https://pip.pypa.io/warnings/backtracking for guidance. If you want to abort this run, press Ctrl + C.
INFO: pip is looking at multiple versions of nvidia-cusolver-cu12 to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of nvidia-cufft-cu12 to determine which version is compatible with other requirements. This could take a while.
Collecting nvidia-cufft-cu12==11.3.3.83
  Using cached nvidia_cufft_cu12-11.3.3.83-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (193.1 MB)
INFO: This is taking longer than usual. You might need to provide the dependency resolver with stricter constraints to reduce runtime. See https://pip.pypa.io/warnings/backtracking for guidance. If you want to abort this run, press Ctrl + C.
INFO: pip is looking at multiple versions of nvidia-curand-cu12 to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of nvidia-cudnn-cu12 to determine which version is compatible with other requirements. This could take a while.

**After 1 hour, the progress was this:** 

Collecting nvidia-cudnn-cu12==9.10.2.21
  Using cached nvidia_cudnn_cu12-9.10.2.21-py3-none-manylinux_2_27_x86_64.whl (706.8 MB)
INFO: This is taking longer than usual. You might need to provide the dependency resolver with stricter constraints to reduce runtime. See https://pip.pypa.io/warnings/backtracking for guidance. If you want to abort this run, press Ctrl + C.
INFO: pip is looking at multiple versions of nvidia-cufile-cu12 to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of nvidia-cuda-runtime-cu12 to determine which version is compatible with other requirements. This could take a while.
Collecting nvidia-cuda-runtime-cu12==12.8.90
  Using cached nvidia_cuda_runtime_cu12-12.8.90-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (954 kB)

I appreciate any advice on the template or machine chosen; perhaps there is a configuration that works better.
Thanks!!

**Comment by eariel** [comment]
**UPDATE**: At the end, after more than 3 hours, I get this error and I was not able to start Fluxgym, a lot of "module not found" errors:

Collecting nvidia-cuda-nvrtc-cu12==12.8.93
  Using cached nvidia_cuda_nvrtc_cu12-12.8.93-py3-none-manylinux2010_x86_64.manylinux_2_12_x86_64.whl (88.0 MB)
INFO: This is taking longer than usual. You might need to provide the dependency resolver with stricter constraints to reduce runtime. See https://pip.pypa.io/warnings/backtracking for guidance. If you want to abort this run, press Ctrl + C.
ERROR: Exception:
Traceback (most recent call last):
  File "/workspace/fluxgym/env/lib/python3.10/site-packages/pip/_internal/cli/base_command.py", line 165, in exc_logging_wrapper
    status = run_func(*args)
  File "/workspace/fluxgym/env/lib/python3.10/site-packages/pip/_internal/cli/req_command.py", line 205, in wrapper
    return func(self, options, args)
  File "/workspace/fluxgym/env/lib/python3.10/site-packages/pip/_internal/commands/install.py", line 339, in run
    requirement_set = resolver.resolve(
  File "/workspace/fluxgym/env/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 94, in resolve
    result = self._result = resolver.resolve(
  File "/workspace/fluxgym/env/lib/python3.10/site-packages/pip/_vendor/resolvelib/resolvers.py", line 481, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "/workspace/fluxgym/env/lib/python3.10/site-packages/pip/_vendor/resolvelib/resolvers.py", line 392, in resolve
    raise ResolutionTooDeep(max_rounds)
pip._vendor.resolvelib.resolvers.ResolutionTooDeep: 2000000
(env) root@18765e38adba:/workspace/fluxgym#

**Comment by DaRoamer** [comment]
I had the same issue.  Realized the problem was the included version of pip was old.  It was v22.2.1.  Did python.exe -m pip install --upgrade pip, which updated it to v25.2 and it finished doing all the requirements in a couple of minutes.

**Comment by Dees-Emporium** [comment]
I have encountered the same issue you mention during the previous few times I attempted training a LoRA using Runpod. This is a fairly recent issue for me, however, because I have successfully trained 20-30 models between 3 and 6 months ago. If you open to trying a different Runpod template, the following worked for me on the first attempt and installing is really straight forward. It's a recent guide (01-09-2025), published on CivitAI by [Midnightkidnaper]. It's called:

**The Definitive Guide: A Detailed Walkthrough for Training Character LoRAs [RUNPOD TEMPLATE]**

The link for it is here: 
[A Detailed Walkthrough for Training Character LoRAs [RUNPOD TEMPLATE]](https://civitai.com/articles/18920/the-definitive-guide-a-detailed-walkthrough-for-training-character-loras-runpod-template)
